# The URL the site will be built for
base_url = "https://corona.leotsarev.ru/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false


theme = "hyde"

description = "ролевиков болеет коронавирусом."

title = "0"

[extra]
# Put all your custom variables here

hyde_reverse = true

hyde_links = [
    {url = "/", name = "Коронавирус и РИ"},
    {url = "/links", name = "Общеполезные ссылки"},
    {url = "/comcon", name = "Комкон (23 марта)"},
    {url = "/cancel-games", name = "Что с играми? (23 марта)"},
]
